### ISSUE TITLE
add site www1.lucienmann.pro and www1.sherwoodsutton.pro

### ISSUE THREAD

**Issue by Starmania** [xXNurioXx/Ads-Link-Skiper#14]
the link is in the adress
EX : https://www1.sherwoodsutton.pro/pushredirect/?network=2&site=adfly&ppi=3830034&pci=4790934151&t=1571223285&dest= **https%3A%2F%2Fmc-launcher.com%2Ffiles%2Func%2FFeedTheBeast.jar**

**Comment by Starmania** [comment]
official link : https://mc-launcher.com/files/unc/FeedTheBeast.jar

**Comment by nuriofernandez** [comment]
Hi Starmania!

I will take a look at that shortener soon. Thank you for reporting it. :)
