### ISSUE TITLE
how to update from 1.7.2 to 1.7.3

### ISSUE THREAD

**Issue by WeWeM** [xXNurioXx/Ads-Link-Skiper#17]
hello
how to update from 1.7.2 to 1.7.3
or if you could  give me a CRX File

**Comment by nuriofernandez** [comment]
Google Chrome store has removed this extension cause of his privacy policy. I need to update the extension permissions to be more specific and create a document explaining why the extension needs these permissions.

Also, if you want, you can generate a CRX file or load the extension unpacked at `chrome://extensions/`
