### ISSUE TITLE
Update the project code to the ES6 standard

### ISSUE THREAD

**Issue by nuriofernandez** [xXNurioXx/Ads-Link-Skiper#24]

**Comment by PushpenderSaini0** [comment]
Hi i would like to work on this .
I will convert all the variable declaration to `let` and `const`
and convert the functions to `arrow functions`
will that be fine ?

**Comment by nuriofernandez** [comment]
Hi @PushpenderSaini0! 👋

Yes, it will be fine! Just take care with letting things better than you found, try to create small pieces of code, and divide your work into commits with explanatory comments! 😊
