### ISSUE TITLE
Uncaught ReferenceError: code is not defined

### ISSUE THREAD

**Issue by PushpenderSaini0** [xXNurioXx/Ads-Link-Skiper#25]
I keep getting this code not defined error !
a variable `code` is used but not defined. 
in file `/src/js/sites/adfly.js`

![image](https://user-images.githubusercontent.com/54404738/122705551-9e123f00-d273-11eb-9a84-09f24a74d537.png)

I think the `if condition` should be inside the `skip` function , which fixes the error !
Should i submit a PR to solve this error ?

**Comment by nuriofernandez** [comment]
Thank you for reporting this issue, cause I have merged the second pull request you launched before reviewing this ticket, I merged it with the changes of this issue. So, I updated the commit history to include the issue id at that commit!

Be careful with updating your fork, you should reset it to match the new history. 🔝
