### ISSUE TITLE
ouo.io doesn't work anymore

### ISSUE THREAD

**Issue by 775405984** [xXNurioXx/Ads-Link-Skiper#4]
since the latest update

**Comment by nuriofernandez** [comment]
Hi! ouo.io has updated a long time ago, with this update i can't bypass recaptcha again. Because that update, Ads Link Skiper just skip the count down to decrease the waiting time.

Do you mean that the countdown is still present?

**Comment by 775405984** [comment]
I know this extension can't bypass anymore, and I've made peace with that.
The problem is clicking the "I'M A HUMAN" button doesn't take me to the next page when Ads-Link-Skipper was turned on.
This problem started today since it automatically updated to the latest version, 1.4.13.

@xXNurioXx

**Comment by nuriofernandez** [comment]
It's working for me. Can you send me the ouo.io link?

**Comment by nuriofernandez** [comment]
Hey! It's all right jet? @775405984

**Comment by 775405984** [comment]
it's fine now @xXNurioXx
